project:
  type: website
  resources:
  - CNAME

website:
  favicon: Images/Footy_forest_favicon_logo.png
  title: "The Footy Forest"
  open-graph: true
  announcement: 
    dismissable: false
    content: <font color="white">  A machine learning model that predicts the winners of AFL football matches</font>
    type: secondary
    position: below-navbar
  navbar:
    logo: Images/Footy_forest_simple_logo.png
    left:
      - text: "About"
        href: about.qmd
      - text: "Team power rankings"
        href: dashboard.qmd
      - text: "Blog"
        href: blog.qmd
    right: 
      - icon: github
        href: https://github.com/mattnurse
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=61559518431071
        
        

format:
  html:
    theme: [morph, custom.scss]
    toc: true
    page-layout: full 
    date-format: "D-MMMM-YYYY" # Example: 7 July 2024
  
    




