project:
  type: website

website:
  title: "The Footy Forest"
  open-graph: true
  announcement: 
    icon: info-circle
    dismissable: false
    content: "A machine learning model that predicts the winners of AFL football matches"
    type: secondary
    position: below-navbar
  navbar:
    logo: Images/Footy_forest_simple_logo.png
    left:
      - text: "About"
        href: about.qmd
      - text: "Team power rankings"
        href: dashboard.qmd
      - text: "Blog"
        href: blog.qmd
    right: 
      - icon: github
        href: https://github.com/mattnurse
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=61559518431071
        
        

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true
    page-layout: full 



