project:
  type: website

website:
  title: "The Footy Forest"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: dashboard.qmd
        text: Team power rankings
      - href: blog.qmd
        text: Blog
        

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true



