project:
  type: website

website:
  title: "The Footy Forest"
  open-graph: true
  announcement: 
    icon: info-circle
    dismissable: false
    content: "A machine learning model that predicts the winners of AFL football matches"
    type: secondary
    position: below-navbar
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: dashboard.qmd
        text: Team power rankings
      - href: blog.qmd
        text: Blog
        

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true
    page-layout: full



