on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: '* 7,9,10,13,20 * 3-9 *'

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Install curl
        run: sudo apt install curl
        
      - name: Install libcurl4
        run: sudo apt-get install libcurl4-openssl-dev
        
      - name: Install libmagick
        run: sudo apt-get install libmagick++-dev
        
      - name: Install libfribidi etc for textshaping package
        run: sudo apt install libharfbuzz-dev libfribidi-dev libtiff5-dev

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}